on:
  push:
    branches:
      - "main"
name: 🚀 Deploy website on push
jobs:
  # avoid-redundancy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cancel Previous Runs
  #       uses: styfle/cancel-workflow-action
  #       with:
  #         workflow_id: all

  install-dependencies:
    name: 🎉 Build
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.19'
        extensions: mbstring, dom, fileinfo, mysql, gd, opcache, intl, mbstring, zip, exif, pcntl, bcmath, gd, mysqli, pdo_mysql

    - name: Get Composer cache directory
      id: composer-cache1
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Get Composer cache
      uses: actions/cache@v3.0.2
      id: composer-cache
      with:
        path: ${{ steps.composer-cache1.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - uses: actions/setup-node@v3.1.1
      with:
        node-version: lts/*
    - name: Get node version
      id: node
      run: |
        echo "::set-output name=version::$(node -v)"
    - name: Get node_modules cache
      uses: actions/cache@v3.0.2
      id: node_modules
      with:
        path: |
          **/node_modules
        # Adding node version as cache key
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}
    - run: npm ci
    - run: npm run build

    - uses: actions/upload-artifact@v4
      with:
        name: proyecto
        path: / # or path/to/artifact

  deploy-cpanel:
    needs: ['install-dependencies']
    runs-on: ubuntu-latest
    steps:
    - name: Obtener codigo
      uses: actions/upload-artifact@v4
      with:
        name: proyecto
        path: / # or path/to/artifact
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.dirislimasur.gob.pe
        username: capacitaciones@capacitaciones.dirislimasur.gob.pe
        password: Daregu3005
        exclude: |
          **/vendor/**
          **/.git*/**
          **/node_modules/**